name: Java/HMCL CI

on:
  push:
  pull_request:

jobs:
  java-hmcl:
    name: DSHCraft Java/HMCL
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hmcl-ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Build GPL Java/HMCL product
        run: ./gradlew :HMCL:build --no-daemon
